[package]
name = "belalang_interactive_debug"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"
authors = ["Vito Secona <secona00@gmail.com>"]

[dependencies]
belalang_compiler.workspace = true
belalang_vm.workspace = true
thiserror.workspace = true
